services:
  api-tests-dev:
    build: .
    image: mtararujs/api-tests
    container_name: api-tests-dev
    volumes:
      - $PWD/test-reports/dev:/api-tests/mochawesome-report
    # command: [ "run", "BOOKS", "BOOKS_DEV" ]
    command: run BOOKS BOOKS_DEV
    networks:
      - sample-book-app-compose-network
  api-tests-stg:
    build: .
    image: mtararujs/api-tests
    container_name: api-tests-stg
    volumes:
      - $PWD/test-reports/stg:/api-tests/mochawesome-report
    command: run BOOKS BOOKS_STG
    networks:
      - sample-book-app-compose-network
  api-tests-prd:
    build: .
    image: mtararujs/api-tests
    container_name: api-tests-prd
    volumes:
      - $PWD/test-reports/prd:/api-tests/mochawesome-report
    command: run BOOKS BOOKS_PRD
    networks:
      - sample-book-app-compose-network

networks:
  sample-book-app-compose-network:
    external: true
 


# docker run --rm --network sample-book-app-network -v $PWD/test-reports:/api-tests/mochawesome-report api-tests