name: api-test

on:
  push:
    branches:
      - 'ci/cd'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Debug Secrets
      run: |
        echo ${{secrets.DOCKERHUB_NAME}}
        echo ${{secrets.DOCKERHUB_PASSWORD}}

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_NAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKERHUB_NAME }}/api-tests:latest .

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKERHUB_NAME }}/api-tests:latest
